{
 "title": "Windows Base",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "query": "${VAR_JOB}" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "label_values(go_goroutines{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "content": "\n# About This Dashboard\n\nThis dashboard is the base dashboard for Windows which covers performance for below objects:\n\n- CPU\n- Memory\n- Network\n- Local Disk\n- Cluster Volume\n\nUsers should **pick panels based on their own requirements**.\n\n# Prometheus Exporter\n\nMetrics are colleced by leveraging [telegraf](https://www.influxdata.com/time-series-platform/telegraf/) from Influxdata. A skeleton configuration file can be generated as below:\n\n```bash\n .\\telegraf.exe --section-filter agent:inputs:outputs --input-filter win_perf_counters --output-filter prometheus_client config > telegraf.conf\n```\n\n**Notes**: The configuration skeleton generated can not be used directly since it is not encoded as UTF-8. Use Notepad++ or other software to conver the encoding.\n\n# Reference\n\n- [Running Telegraf as a Windows Service](https://github.com/influxdata/telegraf/blob/master/docs/WINDOWS_SERVICE.md)\n- [Monitoring Windows Services with Grafana, InfluxDB and Telegraf](https://www.influxdata.com/blog/monitoring-windows-services-with-grafana-influxdb-and-telegraf)"
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "win_cpu_Percent_Processor_Time{instance=~\"$hostname\", exported_instance=\"_Total\", job=\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "% ProcessorTime({{ host }})",
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Privileged_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Priviledged Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% User Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Interrupt Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Processor Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "expr": "win_cpu_Percent_Privileged_Time{instance=~\"$hostname\", exported_instance=\"_Total\", job=\"$job\"}",
     "legendFormat": "% PrivilegedTime({{ host }})"
    },
    {
     "expr": "win_cpu_Percent_User_Time{instance=~\"$hostname\", exported_instance=\"_Total\", job=\"$job\"}",
     "legendFormat": "% UserTime({{ host }})"
    },
    {
     "expr": "win_cpu_Percent_Interrupt_Time{instance=~\"$hostname\", exported_instance=\"_Total\", job=\"$job\"}",
     "legendFormat": "% InterruptTime({{ host }})"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "processes",
     "expr": "win_system_Processes{instance=~\"$hostname\", job=\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Processes({{ host }})",
     "query": "win_system_Processes{instance=\"$hostname\",job=\"windows\"}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Processor Queue",
     "expr": "win_system_Processor_Queue_Length{instance=~\"$hostname\", job=\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "ProcessorQueue({{ host }})",
     "query": "SELECT mean(\"Processor_Queue_Length\") FROM \"win_system\" WHERE \"host\" =~ /^$hostname$/ AND \"objectname\" = 'System' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "threads",
     "expr": "win_system_Threads{instance=~\"$hostname\", job=\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Threads({{ host }})",
     "query": "SELECT mean(\"Threads\") FROM \"win_system\" WHERE \"host\" =~ /^$hostname$/ AND \"objectname\" = 'System' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "avg_over_time(win_mem_Available_Bytes{instance=~\"$hostname\", job=\"$job\"}[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Available Bytes({{ host }})",
     "query": "SELECT mean(\"Available_Bytes\") as \"Available Bytes\", mean(\"Pool_Nonpaged_Bytes\") as \"Pool Nonpaged Bytes\", mean(\"Pool_Paged_Bytes\") as \"Pool Paged Bytes\" FROM \"win_mem\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg_over_time(win_mem_Pool_Nonpaged_Bytes{instance=~\"$hostname\", job=\"$job\"}[1m])",
     "legendFormat": "Pool Nonpaged Bytes({{ host }})"
    },
    {
     "expr": "avg_over_time(win_mem_Pool_Paged_Bytes{instance=~\"$hostname\", job=\"$job\"}[1m])",
     "legendFormat": "Pool Paged Bytes({{ host }})"
    }
   ]
  },
  {
   "title": "Memory Usage Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "avg_over_time(win_mem_Cache_Faults_persec{instance=~\"$hostname\", job=\"$job\"}[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Cache Faults persec({{ host }})",
     "query": "SELECT mean(\"Cache_Faults_persec\") as \"Cache Faults persec\", mean(\"Demand_Zero_Faults_persec\") as \"Demand Zero Faults persec\", mean(\"Page_Faults_persec\") as \"Page Faults persec\", mean(\"Pages_persec\") as \"Pages persec\", mean(\"Transition_Faults_persec\") as \"Transition Faults persec\" FROM \"win_mem\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(0) ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg_over_time(win_mem_Demand_Zero_Faults_persec{instance=~\"$hostname\", job=\"$job\"}[1m])",
     "legendFormat": "Demand Zero Faults persec({{ host }})"
    },
    {
     "expr": "avg_over_time(win_mem_Page_Faults_persec{instance=~\"$hostname\", job=\"$job\"}[1m])",
     "legendFormat": "Page Faults persec({{ host }})"
    }
   ]
  },
  {
   "title": "System Paging",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "avg_over_time(win_mem_Pages_persec{instance=~\"$hostname\", job=\"$job\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Pages/sec({{ host }})",
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Pages_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Pages/sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Page_Faults_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Page_Faults/sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Page_Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Page_Reads/sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Page_Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Page_Writes/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "expr": "avg_over_time(win_mem_Page_Faults_persec{instance=~\"$hostname\", job=\"$job\"}[1m])",
     "legendFormat": "Pages_Faults/sec({{ host }})"
    },
    {
     "expr": "avg_over_time(win_mem_Page_Reads_persec{instance=~\"$hostname\", job=\"$job\"}[1m])",
     "legendFormat": "Pages_Reads/sec({{ host }})"
    },
    {
     "expr": "avg_over_time(win_mem_Page_Writes_persec{instance=~\"$hostname\", job=\"$job\"}[1m])",
     "legendFormat": "Pages_writes/sec({{ host }})"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "expr": "avg_over_time(win_system_Context_Switches_persec{instance=~\"$hostname\", job=\"$job\"}[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Context Switches persec({{ host }})",
     "query": "SELECT mean(\"Context_Switches_persec\") AS \"Context Switches persec\" FROM \"win_system\" WHERE \"host\" =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "expr": "avg_over_time(win_system_System_Calls_persec{instance=~\"$hostname\", job=\"$job\"}[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "System Calls/sec({{ host }})",
     "query": "SELECT mean(\"System_Calls_persec\") AS \"System Calls / sec\" FROM \"win_system\" WHERE \"host\" =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$hostname: $col",
     "expr": "avg_over_time(win_net_Bytes_Received_persec{instance=~\"$hostname\",job=\"$job\"}[30s])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{exported_instance}} Bytes Received({{ host }})",
     "query": "SELECT mean(\"Bytes_Received_persec\") AS \"Bytes Received persec\", mean(\"Bytes_Sent_persec\") AS \"Bytes Sent persec\" FROM \"win_net\" WHERE \"host\" =~ /$hostname$/ AND \"instance\" =~ /$network$/  AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$hostname: $col",
     "expr": "avg_over_time(win_net_Bytes_Sent_persec{instance=\"$hostname\",job=\"$job\"}[30s])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{exported_instance}} Bytes Sent({{ host }})",
     "query": "SELECT mean(\"Bytes_Received_persec\") AS \"Bytes Received persec\", mean(\"Bytes_Sent_persec\") AS \"Bytes Sent persec\" FROM \"win_net\" WHERE \"host\" =~ /$hostname$/ AND \"instance\" =~ /$network$/  AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$hostname: $col",
     "expr": "avg_over_time(win_net_Packets_Received_persec{instance=~\"$hostname\",job=\"$job\"}[30s])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{exported_instance}} Packets Received({{ host }})",
     "query": "SELECT mean(\"Bytes_Received_persec\") AS \"Bytes Received persec\", mean(\"Bytes_Sent_persec\") AS \"Bytes Sent persec\" FROM \"win_net\" WHERE \"host\" =~ /$hostname$/ AND \"instance\" =~ /$network$/  AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$hostname: $col",
     "expr": "avg_over_time(win_net_Packets_Sent_persec{instance=~\"$hostname\",job=\"$job\"}[30s])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{exported_instance}} Packets Sent({{ host }})",
     "query": "SELECT mean(\"Bytes_Received_persec\") AS \"Bytes Received persec\", mean(\"Bytes_Sent_persec\") AS \"Bytes Sent persec\" FROM \"win_net\" WHERE \"host\" =~ /$hostname$/ AND \"instance\" =~ /$network$/  AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Package Drop",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(win_net_Packets_Received_Discarded{instance=~\"$hostname\",job=\"$job\"}[30s])",
     "legendFormat": "{{ exported_instance }} In({{ host }})"
    },
    {
     "expr": "avg_over_time(win_net_Packets_Outbound_Discarded{instance=\"$hostname\",job=\"$job\"}[30s])",
     "legendFormat": "{{ exported_instance }} Out({{ host }})"
    }
   ]
  },
  {
   "title": "Package Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(win_net_Packets_Received_Errors{instance=~\"$hostname\",job=\"$job\"}[30s])",
     "legendFormat": "{{ exported_instance }} In({{ host }})"
    },
    {
     "expr": "avg_over_time(win_net_Packets_Outbound_Errors{instance=\"$hostname\",job=\"$job\"}[30s])",
     "legendFormat": "{{ exported_instance }} Out({{ host }})"
    }
   ]
  },
  { "title": "Local Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "win_disk_Disk_Reads_persec{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }}({{ host }})"
    },
    {
     "expr": "win_disk_Disk_Writes_persec{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }}({{ host }})"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "win_disk_Disk_Read_Bytes_persec{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }}({{ host }})"
    },
    {
     "expr": "win_disk_Disk_Write_Bytes_persec{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }}({{ host }})"
    }
   ]
  },
  {
   "title": "% Disk R/W Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "win_disk_Percent_Disk_Read_Time{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }}({{ host }})"
    },
    {
     "expr": "win_disk_Percent_Disk_Write_Time{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }}({{ host }})"
    }
   ]
  },
  { "title": "Cluster File System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "cluster_csv_filesystem_Reads_persec{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }} R({{ host }})"
    },
    {
     "expr": "cluster_csv_filesystem_Writes_persec{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }} W({{ host }})"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "cluster_csv_filesystem_IO_Read_Bytes_persec{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }} R({{ host }})"
    },
    {
     "expr": "cluster_csv_filesystem_IO_Write_Bytes_persec{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }} W({{ host }})"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "cluster_csv_filesystem_Read_Latency{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }} R({{ host }})"
    },
    {
     "expr": "cluster_csv_filesystem_Write_Latency{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }} W({{ host }})"
    }
   ]
  },
  {
   "title": "Redirect IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "cluster_csv_filesystem_Redirected_Reads_persec{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }} R({{ host }})"
    },
    {
     "expr": "cluster_csv_filesystem_Redirected_Writes_persec{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }} W({{ host }})"
    }
   ]
  },
  {
   "title": "Redirect Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "cluster_csv_filesystem_Redirected_Read_Bytes_persec{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }} R({{ host }})"
    },
    {
     "expr": "cluster_csv_filesystem_Redirected_Read_Bytes_persec{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }} W({{ host }})"
    }
   ]
  },
  {
   "title": "Redirect Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "cluster_csv_filesystem_Redirected_Read_Latency{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }} R({{ host }})"
    },
    {
     "expr": "cluster_csv_filesystem_Redirected_Write_Latency{instance=~\"$hostname\",job=\"$job\"}",
     "legendFormat": "{{ exported_instance }} W({{ host }})"
    }
   ]
  }
 ]
}