{
 "title": "MS SQL Base",
 "description": "Dashboard for Microsoft SQL server with Prometheus and Telegraf SQL plugin version 2.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "${VAR_JOB}" },
   {
    "name": "sql_instance",
    "label": "SQL instance",
    "query": "label_values(sqlserver_server_properties_uptime{job=\"$job\"},sql_instance) "
   },
   {
    "name": "database_name",
    "label": "Database",
    "query": "label_values(sqlserver_database_io_read_bytes{job=\"$job\",sql_instance=~\"$sql_instance\"}, database_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 0 },
   "content": "\n# About This Dashboard\n\nThis dashboard is the base dashboard for MS SQL. Users should **pick panels based on their own requirements**.\n\n# Prometheus Exporter\n\nMetrics are colleced by leveraging [telegraf](https://www.influxdata.com/time-series-platform/telegraf/) from Influxdata. A skeleton configuration file can be generated as below:\n\n```bash\n telegraf --section-filter agent:inputs:outputs --input-filter sqlserver --output-filter prometheus_client config > telegraf.conf\n```\n\n# Configure\n\n**SQL Server**\n\nAn login user needs to be created for the SQL Servers. Refer to [SQL Server Input Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/sqlserver) for steps on how to create a login.\n\n**Telegraf**\n\nRefer to the sample named telegraf.conf under the same directory of this README.\n"
  },
  {
   "title": "Global requests per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance_value{job=\"$job\",sql_instance=~\"$sql_instance\",counter=\"Batch Requests/sec\"}[5m]))",
     "legendFormat": "Batch Requests/sec"
    },
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance_value{job=\"$job\",sql_instance=~\"$sql_instance\",counter=\"SQL Compilations/sec\"}[5m]))",
     "legendFormat": "SQL Compilations/sec"
    },
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance_value{job=\"$job\",sql_instance=~\"$sql_instance\",counter=\"SQL Re-Compilations/sec\"}[5m]))",
     "legendFormat": "SQL Re-Compilations/sec"
    }
   ]
  },
  {
   "title": "Buffer cache hit ratio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (sqlserver_performance_value{job=\"$job\",sql_instance=~\"$sql_instance\",counter=\"Buffer cache hit ratio\"})",
     "legendFormat": "Buffer cache hit ratio"
    }
   ]
  },
  { "title": "DB filtered metrics", "type": "text", "gridPos": { "h": 1, "w": 20, "x": 0, "y": 17 } },
  {
   "title": "Database size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (sqlserver_performance_value{job=\"$job\",sql_instance=~\"$sql_instance\",database_name=~\"$database_name\",counter=\"Data File(s) Size (KB)\",exported_instance!=\"Total\"})",
     "legendFormat": "Data"
    },
    {
     "expr": "sum by (sql_instance) (sqlserver_performance_value{job=\"$job\",sql_instance=~\"$sql_instance\",database_name=~\"$database_name\",counter=\"Log File(s) Size (KB)\",exported_instance!=\"Total\"})",
     "legendFormat": "TLog"
    }
   ]
  },
  {
   "title": "Transactions per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance_value{job=\"$job\",sql_instance=~\"$sql_instance\",database_name=~\"$database_name\",counter=\"Transactions/sec\",exported_instance!=\"Total\"}[5m]))",
     "legendFormat": "1/s"
    }
   ]
  },
  {
   "title": "Database IO throughout",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_read_bytes{job=\"$job\",sql_instance=~\"$sql_instance\",database_name=~\"$database_name\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_write_bytes{job=\"$job\",sql_instance=~\"$sql_instance\",database_name=~\"$database_name\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Database IO operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_reads{job=\"$job\",sql_instance=~\"$sql_instance\",database_name=~\"$database_name\"}[5m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_writes{job=\"$job\",sql_instance=~\"$sql_instance\",database_name=~\"$database_name\"}[5m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Database IO latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_read_latency_ms{job=\"$job\",sql_instance=~\"$sql_instance\",database_name=~\"$database_name\"}[5m]))",
     "legendFormat": "Read latency"
    },
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_write_latency_ms{job=\"$job\",sql_instance=~\"$sql_instance\",database_name=~\"$database_name\"}[5m]))",
     "legendFormat": "Write latency"
    }
   ]
  },
  {
   "title": "Backup/restore throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance_value{job=\"$job\",sql_instance=~\"$sql_instance\",database_name=~\"$database_name\",counter=\"Backup/Restore Throughput/sec\",exported_instance!=\"Total\"}[5m]))",
     "legendFormat": "Backup/Restore Throughput/sec"
    }
   ]
  }
 ]
}