{
 "title": "Monitoring Infrastructure",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "${VAR_JOB}" },
   {
    "name": "instance",
    "label": "Prometheus",
    "query": "label_values(up{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "\n# About\n\nThis is the dashboard for monitoring the monitoring infrastructure, A.K.A Prometheus servers.\n\n\n\n"
  },
  {
   "title": "Uptime Since Last Config Reload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(time() - prometheus_config_last_reload_success_timestamp_seconds{job=~\"$job\",instance=~\"$instance\"}) / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Samples/Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 3 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "irate(prometheus_tsdb_head_samples_appended_total{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_scrapes_sample_out_of_bounds_total{job=\"$job\",instance=~\"instance\"} + prometheus_target_scrapes_sample_out_of_order_total{job=\"$job\",instance=~\"instance\"} + prometheus_treecache_zookeeper_failures_total{job=\"$job\",instance=~\"instance\"} + prometheus_tsdb_compactions_failed_total{job=\"$job\",instance=~\"instance\"} + prometheus_tsdb_head_series_not_found{job=\"$job\",instance=~\"instance\"} + prometheus_tsdb_reloads_failures_total{job=\"$job\",instance=~\"instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Series Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Series Created|Removed/Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "irate(prometheus_tsdb_head_series_created_total{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}/Created"
    },
    {
     "expr": "irate(prometheus_tsdb_head_series_removed_total{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}/Removed"
    }
   ]
  },
  {
   "title": "Memory Chunks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query Duration - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "repeat": "instance",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_engine_query_duration_seconds_sum{job=\"$job\",instance=~\"$instance\"}) by (slice)",
     "legendFormat": "{{slice}}"
    }
   ]
  }
 ]
}