{
 "title": "Switch Base",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "${VAR_JOB}" },
   {
    "name": "switch",
    "label": "Switch",
    "query": "label_values(sysName{job=\"$job\"}, instance)"
   },
   {
    "name": "ports",
    "label": "Ports",
    "query": "label_values(ifAdminStatus{job=\"$job\",instance=\"$switch\"},ifName)"
   },
   {
    "name": "sw_name",
    "query": "label_values(sysName{job=\"$job\", instance=\"$switch\"}, sysName)"
   }
  ]
 },
 "panels": [
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "content": "\n# About This Dashboard\n\nThis dashboard is the base dashboard for switch covering:\n\n- System Uptime\n- Bandwidth\n- Status\n- Throughput\n- BUM Status\n- Drop\n- Error\n\nUsers should **pick panels based on their own requirements**. By now, Dell Ethernet switch, Cisco MDS switch and Brocade FC switch have been verified.\n\n# Prometheus Exporter\n\nMetrics are colleced by leveraging Prometheus [SNMP Exporter](https://github.com/prometheus/snmp_exporter).\n\n# Reference\n\n- [Sample configurations](https://github.com/kckecheng/prometheus/tree/master/config/snmp_exporter)\n"
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sysUpTime{job=\"$job\", instance=\"$switch\"} / 100"
    }
   ]
  },
  {
   "title": "Bandwidth - $sw_name",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 11 },
   "targets": [
    {
     "expr": "ifHighSpeed{job=\"$job\", instance=\"$switch\"} or ifSpeed{job=\"$job\", instance=\"$switch\"}"
    }
   ]
  },
  {
   "title": "Port Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 11 },
   "targets": [
    {
     "expr": "ifOperStatus{job=\"$job\",instance=\"$switch\"}"
    }
   ]
  },
  {
   "title": "Througput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$job\",instance=\"$switch\",ifName=~\"$ports\"}[5m])",
     "legendFormat": "{{ instance }}/{{ ifName }} - Read"
    },
    {
     "expr": "irate(ifHCOutOctets{job=\"$job\",instance=\"$switch\",ifName=~\"$ports\"}[5m]) ",
     "legendFormat": "{{ instance }}/{{ ifName }} - Write"
    }
   ]
  },
  {
   "title": "BUM",
   "type": "graph",
   "description": "Broadcast, Unknown Unicast and Multicast",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(ifInUnknownProtos{job=\"$job\",instance=\"$switch\",ifName=~\"$ports\"}[5m]) + irate(ifHCInBroadcastPkts{job=\"$job\",instance=\"$switch\",ifName=~\"$ports\"}[5m]) + irate(ifHCInMulticastPkts{job=\"$job\",instance=\"$switch\",ifName=~\"$ports\"}[5m])",
     "legendFormat": "{{ instance }}/{{ ifName }} - Read"
    },
    {
     "expr": "irate(ifHCOutBroadcastPkts{job=\"$job\",instance=\"$switch\",ifName=~\"$ports\"}[5m]) + irate(ifHCOutMulticastPkts{job=\"$job\",instance=\"$switch\",ifName=~\"$ports\"}[5m])",
     "legendFormat": "{{ instance }}/{{ ifName }} - Write"
    }
   ]
  },
  {
   "title": "Drop",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(ifInDiscards{job=\"$job\",instance=\"$switch\",ifName=~\"$ports\"}[5m])",
     "legendFormat": "{{ instance }}/{{ ifName }} - Read"
    },
    {
     "expr": "irate(ifOutDiscards{job=\"$job\",instance=\"$switch\",ifName=~\"$ports\"}[5m])",
     "legendFormat": "{{ instance }}/{{ ifName }} - Write"
    }
   ]
  },
  {
   "title": "Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(ifInErrors{job=\"$job\",instance=\"$switch\",ifName=~\"$ports\"}[5m])",
     "legendFormat": "{{ instance }}/{{ ifName }} - Read"
    },
    {
     "expr": "irate(ifOutErrors{job=\"$job\",instance=\"$switch\",ifName=~\"$ports\"}[5m])",
     "legendFormat": "{{ instance }}/{{ ifName }} - Write"
    }
   ]
  }
 ]
}