{
 "title": "Unity NAS Solution",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "unity",
    "label": "Unity",
    "query": "label_values(unity_cpu_uptime,unity)"
   },
   {
    "name": "sp",
    "label": "SP",
    "query": "label_values(unity_basic_reads,sp)"
   },
   {
    "name": "hswitch",
    "label": "Host Switch",
    "query": "label_values(sysUpTime,instance)"
   },
   {
    "name": "hinterface",
    "label": "Host Interface",
    "query": "label_values(ifHighSpeed{instance=~\"$hswitch\"},ifName)"
   },
   {
    "name": "sswitch",
    "label": "Storage Switch",
    "query": "label_values(sysUpTime,instance)"
   },
   {
    "name": "sinterface",
    "label": "Storage Interface",
    "query": "label_values(ifHighSpeed{instance=~\"$sswitch\"},ifName)"
   },
   {
    "name": "vcenter",
    "label": "vCenter",
    "query": "label_values(vmware_host_power_state,instance)"
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": "label_values(vmware_host_power_state{instance=~\"$vcenter\"},dc_name)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(vmware_host_power_state{instance=~\"$vcenter\",dc_name=~\"$datacenter\"}, cluster_name)"
   },
   {
    "name": "esxi",
    "label": "vSphere",
    "query": "label_values(vmware_host_power_state{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\"},host_name)"
   }
  ]
 },
 "panels": [
  { "title": "Unity Array", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "unity" },
  {
   "title": "$unity $sp uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "repeat": "sp",
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "unity_cpu_uptime{sp=\"$sp\",unity=\"$unity\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "$unity $sp Average Basic R/W",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 3, "y": 1 },
   "repeat": "sp",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unity_basic_reads{sp=~\"$sp\",unity=~\"$unity\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "unity_basic_writes{sp=~\"$sp\",unity=~\"$unity\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Thread - $unity $sp",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 1 },
   "repeat": "sp",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unity_currentThreads{unity=\"$unity\",sp=\"$sp\"}",
     "legendFormat": "Num. of Threads($sp)"
    }
   ]
  },
  {
   "title": "$unity $sp uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "unity_cpu_uptime{sp=\"$sp\",unity=\"$unity\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "$unity $sp Average Basic R/W",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unity_basic_reads{sp=~\"$sp\",unity=~\"$unity\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "unity_basic_writes{sp=~\"$sp\",unity=~\"$unity\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Thread - $unity $sp",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unity_currentThreads{unity=\"$unity\",sp=\"$sp\"}",
     "legendFormat": "Num. of Threads($sp)"
    }
   ]
  },
  {
   "title": "Dell Switch Host Side - $hswitch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "switch"
  },
  {
   "title": "Uptime - $hswitch",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "format": "dtdurationms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sysUpTime{instance=~\"$hswitch\"}"
    }
   ]
  },
  {
   "title": "CPU Usage - $hswitch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dellNetCpuUtil5Min{instance=~\"$hswitch\"}",
     "legendFormat": "Avg CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage - $hswitch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": " dellNetCpuUtilMemUsage{instance=~\"$hswitch\"}",
     "legendFormat": "Avg Memory Usage"
    }
   ]
  },
  {
   "title": "Errors and Discards - $hinterface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "repeat": "hinterface",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ifInErrors{instance=\"$hswitch\",ifName=\"$hinterface\"} + ifOutErrors{instance=\"$hswitch\",ifName=\"$hinterface\"}",
     "legendFormat": "Errors "
    },
    {
     "expr": "ifInDiscards{instance=\"$hswitch\",ifName=\"$hinterface\"} + ifOutDiscards{instance=\"$hswitch\",ifName=\"$hinterface\"}",
     "legendFormat": "Discards"
    }
   ]
  },
  {
   "title": "Errors and Discards - $hinterface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ifInErrors{instance=\"$hswitch\",ifName=\"$hinterface\"} + ifOutErrors{instance=\"$hswitch\",ifName=\"$hinterface\"}",
     "legendFormat": "Errors "
    },
    {
     "expr": "ifInDiscards{instance=\"$hswitch\",ifName=\"$hinterface\"} + ifOutDiscards{instance=\"$hswitch\",ifName=\"$hinterface\"}",
     "legendFormat": "Discards"
    }
   ]
  },
  {
   "title": "Throughput - $hinterface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "repeat": "hinterface",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"$hswitch\",ifName=\"$hinterface\"}[5m])  or irate(ifInOctets{instance=\"$hswitch\",ifName=\"$hinterface\"}[5m]) ",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifHCOutOctets{instance=\"$hswitch\",ifName=\"$hinterface\"}[5m])  or irate(ifInOctets{instance=\"$hswitch\",ifName=\"$hinterface\"}[5m]) ",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Throughput - $hinterface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"$hswitch\",ifName=\"$hinterface\"}[5m])  or irate(ifInOctets{instance=\"$hswitch\",ifName=\"$hinterface\"}[5m]) ",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifHCOutOctets{instance=\"$hswitch\",ifName=\"$hinterface\"}[5m])  or irate(ifInOctets{instance=\"$hswitch\",ifName=\"$hinterface\"}[5m]) ",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Dell Swtich Storage Side - $sswitch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "title": "Uptime - $sswitch",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 39 },
   "format": "dtdurationms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sysUpTime{instance=~\"$sswitch\"}"
    }
   ]
  },
  {
   "title": "CPU Usage - $sswitch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dellNetCpuUtil5Min{instance=~\"$sswitch\"}",
     "legendFormat": "Avg CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage - $sswitch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": " dellNetCpuUtilMemUsage{instance=~\"$sswitch\"}",
     "legendFormat": "Avg Memory Usage"
    }
   ]
  },
  {
   "title": "Errors and Discards - $sinterface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "repeat": "sinterface",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ifInErrors{instance=\"$sswitch\",ifName=\"$sinterface\"} + ifOutErrors{instance=\"$sswitch\",ifName=\"$sinterface\"}",
     "legendFormat": "Errors "
    },
    {
     "expr": "ifInDiscards{instance=\"$sswitch\",ifName=\"$sinterface\"} + ifOutDiscards{instance=\"$sswitch\",ifName=\"$sinterface\"}",
     "legendFormat": "Discards"
    }
   ]
  },
  {
   "title": "Throughput - $sinterface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "repeat": "sinterface",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"$sswitch\",ifName=\"$sinterface\"}[5m])  or irate(ifInOctets{instance=\"$sswitch\",ifName=\"$sinterface\"}[5m]) ",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifHCOutOctets{instance=\"$sswitch\",ifName=\"$sinterface\"}[5m])  or irate(ifInOctets{instance=\"$sswitch\",ifName=\"$sinterface\"}[5m]) ",
     "legendFormat": "Out"
    }
   ]
  },
  { "title": "VMware vSphere", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 }, "repeat": "vcenter" },
  {
   "title": "vSphere Host Uptime  - $esxi",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 62 },
   "repeat": "esxi",
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "vmware_host_boot_timestamp_seconds{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "CPU Usage - $esxi",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 62 },
   "repeat": "esxi",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vmware_host_cpu_usage{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"} / vmware_host_cpu_max{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage - $esxi",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 62 },
   "repeat": "esxi",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vmware_host_memory_usage{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"} / vmware_host_memory_max{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "vSphere Host Uptime  - $esxi",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 69 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "vmware_host_boot_timestamp_seconds{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "CPU Usage - $esxi",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 69 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vmware_host_cpu_usage{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"} / vmware_host_cpu_max{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage - $esxi",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 69 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vmware_host_memory_usage{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"} / vmware_host_memory_max{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Host R/W - $esxi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "repeat": "esxi",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vmware_host_disk_read_average{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "vmware_host_disk_write_average{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "VM R/W - $esxi(all VMs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "repeat": "esxi",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vm_disk_read_average{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(vmware_vm_disk_write_average{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"})",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Host R/W - $esxi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vmware_host_disk_read_average{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "vmware_host_disk_write_average{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "VM R/W - $esxi(all VMs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vm_disk_read_average{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(vmware_vm_disk_write_average{instance=~\"$vcenter\",dc_name=~\"$datacenter\",cluster_name=~\"$cluster\",host_name=~\"$esxi\"})",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}