modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
      tls_config:
        insecure_skip_verify: true
  http_post_2xx:
    prober: http
    http:
      method: POST
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
      tls_config:
        insecure_skip_verify: true
  tcp_connect:
    prober: tcp
    tcp:
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
      tls_config:
        insecure_skip_verify: true
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
      tls: true
      tls_config:
        insecure_skip_verify: true
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
      tls_config:
        insecure_skip_verify: true
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
      tls_config:
        insecure_skip_verify: true
  icmp:
    prober: icmp
    icmp:
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
