{
 "title": "Resource Availability Base",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "exporter",
    "label": "Exporter",
    "query": "label_values(probe_success, exporter)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(up{exporter=~\"$exporter\",job=~\"^blackbox.*\"},job)"
   },
   {
    "name": "targets",
    "label": "targets",
    "query": "label_values(up{exporter=~\"$exporter\",job=~'$job'},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "content": "\n## About\n\nThis dashboard is the base dashbaord for resource (array, server, swtich, etc.) availability check.\n\n## prometheus Exporter\n\nData is generated by leveraging [Blackbox Exporter](https://github.com/prometheus/blackbox_exporter)\n\n## Reference\n\n- [Sample Usage](https://github.com/kckecheng/prometheus/tree/master/config/blackbox_exporter)"
  },
  {
   "title": "Target Status - $targets",
   "type": "table",
   "gridPos": { "h": 16, "w": 7, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{exporter=~\"$exporter\", job=~\"$job\",instance=~\"$targets\"} - 0"
    }
   ]
  },
  {
   "title": "Probe Latency - $targets",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{exporter=~\"$exporter\", job=~\"$job\",instance=~\"$targets\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Online/Total",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum (probe_success{exporter=~\"$exporter\",job=~\"$job\",instance=~\"$targets\"})"
    },
    {
     "expr": "count(probe_success{exporter=~\"$exporter\",job=~\"$job\",instance=~\"$targets\"})"
    }
   ]
  },
  {
   "title": "Availability %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum (probe_success{exporter=~\"$exporter\",job=~\"$job\",instance=~\"$targets\"}) / count(probe_success{exporter=~\"$exporter\",job=~\"$job\",instance=~\"$targets\"}) * 100"
    }
   ]
  }
 ]
}